<?xml version="1.0" encoding="UTF-8"?> 
<!-- DTD for properties --> 
<!DOCTYPE properties [
    <!ELEMENT properties ( comment?, property* ) >
    <!ATTLIST properties version CDATA #FIXED "1.0">
    <!ELEMENT comment (#PCDATA) >
    <!ELEMENT property (#PCDATA) >
    <!ATTLIST property key CDATA #REQUIRED>
]>
<properties>
	<property key="RELOAD">1200</property>
	<property key="DEBUG">true</property>
	<!-- 查询结果中 列名是否大写 -->
	<!-- 
	<property key="IS_UPPER_KEY">false</property>
	-->
	<!-- sql 存放根目录 -->
	<property key="SQL_STORE_DIR">sql</property>
	<!-- 密钥 文件路径 -->
	<property key="DES_KEY_FILE">key.xml</property>
	<!-- 是否显示执行的SQL -->
	<property key="SHOW_SQL">true</property>
	<property key="SHOW_SQL_PARAM">true</property>
	<property key="SHOW_SQL_WHEN_ERROR">false</property>
	<property key="SHOW_SQL_PARAM_WHEN_ERROR">false</property>
	<!-- 默认主键 -->
	<property key="DEFAULT_PRIMARY_KEY">ID</property>
	<!-- 是否更新NULL列 -->
	<property key="IS_UPDATE_NULL_COLUMN">false</property>
	<!-- 是否更新空列 -->
	<property key="IS_UPDATE_EMPTY_COLUMN">false</property>
	<!-- 是否启动默认缓存 ehcache -->
	<property key="IS_USE_CACHE">false</property>
	<property key="ERROR_PAGE_PATH">/WEB-INF/web/common/inc/404.html</property>
</properties>